name: Lint and Prettier

on:
  pull_request:
    branches:
      - main
      - release/**

jobs:
  lint-and-prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run prettier
        run: npm run format

      - name: Run lint
        run: npm run lint

      - name: Run ESLint with auto-fix and enforcement
        run: |
          npx eslint --fix .
          npx eslint --max-warnings=0 .
        if: ${{ failure() }}
